Fix a warning
This patch fixes:

  llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp:602:6: error:
  unused function 'printInstructions' [-Werror,-Wunused-function]