Remove an unused variable (NFC)
/llvm-project/llvm/lib/Target/AMDGPU/SIISelLowering.cpp:3416:9:
 error: unused variable 'ValVT' [-Werror,-Wunused-variable]
    EVT ValVT = VA.getValVT();
        ^
1 error generated.