Fix a warning
This patch fixes:

  lldb/unittests/Protocol/ProtocolMCPServerTest.cpp:285:14: error:
  unused variable 'mutex' [-Werror,-Wunused-variable]